### ISSUE TITLE
run-server excepts going 2.1.16 -> 2.1.(17 | 18)

### ISSUE THREAD

**Issue by verma** [http-kit/http-kit#139]
My program works fine with `2.1.16` for this call

```
 (run-server app {:port 3000}))
```

where `app` is a compojure routing table:

```
(defroutes app-routes
    (GET "/" [] (index-page))
    ... )

(def app
     (-> (site app-routes)
     wrap-base-url
     reload/wrap-reload))
```

`run-server` call is here:
https://github.com/verma/dakait/blob/7d06c0c2cfb0b12877d6d6a94a0524da6508e98e/src/dakait/main.clj

Route definitions for `app` are here:
https://github.com/verma/dakait/blob/7d06c0c2cfb0b12877d6d6a94a0524da6508e98e/src/dakait/handler.clj#L159

The `javax-servlet/servlet-api` is at `2.5`

However the `run-server` call fails with versions `2.1.17` and `2.1.18`:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.httpkit.server.HttpServer.   <init>(Ljava/lang/String;ILorg/httpkit/server/IHandler;II)V
at org.httpkit.server$run_server.invoke(server.clj:8)
at dakait.main$_main.doInvoke(main.clj:10)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.Var.invoke(Var.java:411)
at user$eval5$fn__7.invoke(form-init2911059411170187255.clj:1)
at user$eval5.invoke(form-init2911059411170187255.clj:1)
at clojure.lang.Compiler.eval(Compiler.java:6619)
at clojure.lang.Compiler.eval(Compiler.java:6609)
at clojure.lang.Compiler.load(Compiler.java:7064)
at clojure.lang.Compiler.loadFile(Compiler.java:7020)
at clojure.main$load_script.invoke(main.clj:294)
at clojure.main$init_opt.invoke(main.clj:299)
at clojure.main$initialize.invoke(main.clj:327)
at clojure.main$null_opt.invoke(main.clj:362)
at clojure.main$main.doInvoke(main.clj:440)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at clojure.lang.Var.invoke(Var.java:419)
at clojure.lang.AFn.applyToHelper(AFn.java:163)
at clojure.lang.Var.applyTo(Var.java:532)
at clojure.main.main(main.java:37)
```

Is there a breaking change I need to be aware of or could this be a bug?
